### ISSUE TITLE
workflow execution not terminating

### ISSUE THREAD

**Issue by stefanpedratscher** [FedorSmirnov89/EE-Demo#1]
Hi @FedorSmirnov89 ,

If the input of the atomic function is specified wrongly, the EE will throw the following exception:

````java
Exception in thread "Thread-4" java.lang.IllegalStateException: Stop exception when processing atomic enactable of task addition_Demo
        at at.uibk.dps.ee.control.runnable.AtomicEnactment.run(AtomicEnactment.java:37)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: at.uibk.dps.ee.core.exception.StopException
        at at.uibk.dps.ee.enactables.local.LocalAbstract.checkInputEntry(LocalAbstract.java:96)
        at at.uibk.dps.ee.enactables.local.LocalAbstract.readIntInput(LocalAbstract.java:42)
````

The EE will not stop. It is stuck in some kind of endless loop and weird displaying bug. It would be great if the EE terminates with an appropriate error message (e.g. "Could not find input XY from function YZ").  The EE says always EXECUTING and the next execution cannot start and is in WAITING state.

Additionally it would be great if there is a `STOP` button which allows to abort the current execution.

### Reproduce

Run the `.yaml` workflow with the `.json` input from [wrongAtomic.zip](https://github.com/FedorSmirnov89/EE-Demo/files/5944951/wrongAtomic.zip) to reproduce the error.

**Comment by FedorSmirnov89** [comment]
Hi Stefan :) . Thanks for the message. Yes, you are right. Handling errors within functions is not yet implemented (apart from them throwing the Stopexception which does not provide much information). At the moment right now, the focus is still on implementing the core EE functionality, with the assumption of correctly specified WFs and correct function behavior. Will implement better error handling within the next 3 weeks. Again, thank you for the issue.

**Comment by FedorSmirnov89** [comment]
Okay, with the new EE version, you should be getting a descriptive error message in the above case and also be able to pause/stop the WF execution. Could you please review whether the issue still persists?

**Comment by stefanpedratscher** [comment]
Hi @FedorSmirnov89 , I still get an **null**-exception.

````java
at.uibk.dps.ee.core.exception.FailureException: Problem while enacting the function task addition_Demo
null
at.uibk.dps.ee.core.exception.StopException
        at at.uibk.dps.ee.enactables.local.LocalFunctionAbstract.checkInputEntry(LocalFunctionAbstract.java:90)
        at at.uibk.dps.ee.enactables.local.LocalFunctionAbstract.readIntInput(LocalFunctionAbstract.java:29)
        at at.uibk.dps.ee.enactables.local.calculation.Addition.processInput(Addition.java:20)
        at at.uibk.dps.ee.core.enactable.Enactable.play(Enactable.java:131)
        at at.uibk.dps.ee.enactables.EnactableAtomic.play(EnactableAtomic.java:40)
        at at.uibk.dps.ee.control.agents.AgentEnactment.actualCall(AgentEnactment.java:38)
        at at.uibk.dps.ee.control.agents.AgentTask.call(AgentTask.java:39)
        at at.uibk.dps.ee.control.agents.AgentTask.call(AgentTask.java:12)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
        at at.uibk.dps.ee.core.EeCore.enactWorkflow(EeCore.java:64)
        at at.uibk.dps.ee.guice.starter.EeTask.execute(EeTask.java:23)
        at org.opt4j.core.config.Task.call(Task.java:123)
        at org.opt4j.core.config.Task.call(Task.java:41)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: at.uibk.dps.ee.core.exception.StopException
        at at.uibk.dps.ee.control.management.EmergencyManagerHardStop.emergencyProtocol(EmergencyManagerHardStop.java:49)
        at at.uibk.dps.ee.control.management.EnactmentAgent.processInput(EnactmentAgent.java:101)
        at at.uibk.dps.ee.core.enactable.Enactable.play(Enactable.java:131)
        at at.uibk.dps.ee.core.EeCore.enactWorkflow(EeCore.java:59)
        ... 7 more
````

To reproduce run the attached code
[wrongAtomic.zip](https://github.com/FedorSmirnov89/EE-Demo/files/6068828/wrongAtomic.zip)

**Comment by stefanpedratscher** [comment]
The new changes solved the issue, Thanks!
